// 「Guess the Footballer」题库:Who Are Ya 风格的猜球员游戏用。
// 纯文字属性(国籍/俱乐部/联赛/位置/年龄),不含照片 → 零版权。
// 名字/国籍/俱乐部与 decks.ts 的世界杯身价池一致;额外补 league/position/age。
// 数据为约 2026-06 的近似快照,仅供娱乐,与 FIFA/Transfermarkt 无隶属关系。

export type Position = "GK" | "DEF" | "MID" | "FWD";

export type League =
  | "Premier League"
  | "La Liga"
  | "Serie A"
  | "Bundesliga"
  | "Ligue 1"
  | "Saudi Pro League"
  | "MLS"
  | "Other";

export interface GuessPlayer {
  name: string;
  nationality: string;
  flagCode: string; // flagcdn 码
  club: string;
  league: League;
  position: Position;
  age: number;
}

const p = (
  name: string,
  nationality: string,
  flagCode: string,
  club: string,
  league: League,
  position: Position,
  age: number,
): GuessPlayer => ({ name, nationality, flagCode, club, league, position, age });

export const PLAYERS: GuessPlayer[] = [
  p("Jude Bellingham", "England", "gb-eng", "Real Madrid", "La Liga", "MID", 22),
  p("Erling Haaland", "Norway", "no", "Manchester City", "Premier League", "FWD", 25),
  p("Vinícius Júnior", "Brazil", "br", "Real Madrid", "La Liga", "FWD", 25),
  p("Kylian Mbappé", "France", "fr", "Real Madrid", "La Liga", "FWD", 27),
  p("Lamine Yamal", "Spain", "es", "Barcelona", "La Liga", "FWD", 18),
  p("Jamal Musiala", "Germany", "de", "Bayern Munich", "Bundesliga", "MID", 23),
  p("Florian Wirtz", "Germany", "de", "Liverpool", "Premier League", "MID", 22),
  p("Bukayo Saka", "England", "gb-eng", "Arsenal", "Premier League", "FWD", 24),
  p("Pedri", "Spain", "es", "Barcelona", "La Liga", "MID", 23),
  p("Cole Palmer", "England", "gb-eng", "Chelsea", "Premier League", "MID", 23),
  p("Phil Foden", "England", "gb-eng", "Manchester City", "Premier League", "MID", 25),
  p("Rodri", "Spain", "es", "Manchester City", "Premier League", "MID", 29),
  p("Federico Valverde", "Uruguay", "uy", "Real Madrid", "La Liga", "MID", 27),
  p("Victor Osimhen", "Nigeria", "ng", "Galatasaray", "Other", "FWD", 27),
  p("Khvicha Kvaratskhelia", "Georgia", "ge", "Paris Saint-Germain", "Ligue 1", "FWD", 25),
  p("Declan Rice", "England", "gb-eng", "Arsenal", "Premier League", "MID", 27),
  p("Alexander Isak", "Sweden", "se", "Liverpool", "Premier League", "FWD", 26),
  p("Martin Ødegaard", "Norway", "no", "Arsenal", "Premier League", "MID", 27),
  p("Bruno Guimarães", "Brazil", "br", "Newcastle United", "Premier League", "MID", 28),
  p("Julián Álvarez", "Argentina", "ar", "Atlético Madrid", "La Liga", "FWD", 26),
  p("Gavi", "Spain", "es", "Barcelona", "La Liga", "MID", 21),
  p("Rafael Leão", "Portugal", "pt", "AC Milan", "Serie A", "FWD", 26),
  p("Rodrygo", "Brazil", "br", "Real Madrid", "La Liga", "FWD", 25),
  p("Aurélien Tchouaméni", "France", "fr", "Real Madrid", "La Liga", "MID", 26),
  p("Eduardo Camavinga", "France", "fr", "Real Madrid", "La Liga", "MID", 23),
  p("Vitinha", "Portugal", "pt", "Paris Saint-Germain", "Ligue 1", "MID", 26),
  p("Désiré Doué", "France", "fr", "Paris Saint-Germain", "Ligue 1", "FWD", 20),
  p("Bradley Barcola", "France", "fr", "Paris Saint-Germain", "Ligue 1", "FWD", 23),
  p("Moisés Caicedo", "Ecuador", "ec", "Chelsea", "Premier League", "MID", 24),
  p("Joško Gvardiol", "Croatia", "hr", "Manchester City", "Premier League", "DEF", 24),
  p("Raphinha", "Brazil", "br", "Barcelona", "La Liga", "FWD", 29),
  p("Pau Cubarsí", "Spain", "es", "Barcelona", "La Liga", "DEF", 19),
  p("Lautaro Martínez", "Argentina", "ar", "Inter", "Serie A", "FWD", 28),
  p("Harry Kane", "England", "gb-eng", "Bayern Munich", "Bundesliga", "FWD", 32),
  p("Michael Olise", "France", "fr", "Bayern Munich", "Bundesliga", "FWD", 24),
  p("João Neves", "Portugal", "pt", "Paris Saint-Germain", "Ligue 1", "MID", 21),
  p("Nuno Mendes", "Portugal", "pt", "Paris Saint-Germain", "Ligue 1", "DEF", 23),
  p("Ousmane Dembélé", "France", "fr", "Paris Saint-Germain", "Ligue 1", "FWD", 28),
  p("Enzo Fernández", "Argentina", "ar", "Chelsea", "Premier League", "MID", 25),
  p("Nicolò Barella", "Italy", "it", "Inter", "Serie A", "MID", 29),
  p("Xavi Simons", "Netherlands", "nl", "Tottenham Hotspur", "Premier League", "MID", 22),
  p("William Saliba", "France", "fr", "Arsenal", "Premier League", "DEF", 25),
  p("Cody Gakpo", "Netherlands", "nl", "Liverpool", "Premier League", "FWD", 26),
  p("Ryan Gravenberch", "Netherlands", "nl", "Liverpool", "Premier League", "MID", 23),
  p("Dominik Szoboszlai", "Hungary", "hu", "Liverpool", "Premier League", "MID", 25),
  p("Dani Olmo", "Spain", "es", "Barcelona", "La Liga", "MID", 27),
  p("Jules Koundé", "France", "fr", "Barcelona", "La Liga", "DEF", 27),
  p("Gabriel Magalhães", "Brazil", "br", "Arsenal", "Premier League", "DEF", 28),
  p("Alessandro Bastoni", "Italy", "it", "Inter", "Serie A", "DEF", 26),
  p("Kenan Yıldız", "Turkey", "tr", "Juventus", "Serie A", "FWD", 20),
  p("Kai Havertz", "Germany", "de", "Arsenal", "Premier League", "FWD", 26),
  p("Viktor Gyökeres", "Sweden", "se", "Arsenal", "Premier League", "FWD", 27),
  p("Marcus Thuram", "France", "fr", "Inter", "Serie A", "FWD", 28),
  p("Jérémy Doku", "Belgium", "be", "Manchester City", "Premier League", "FWD", 23),
  p("Alexis Mac Allister", "Argentina", "ar", "Liverpool", "Premier League", "MID", 27),
  p("Savinho", "Brazil", "br", "Manchester City", "Premier League", "FWD", 21),
  p("Arda Güler", "Turkey", "tr", "Real Madrid", "La Liga", "MID", 20),
  p("Trent Alexander-Arnold", "England", "gb-eng", "Real Madrid", "La Liga", "DEF", 27),
  p("Micky van de Ven", "Netherlands", "nl", "Tottenham Hotspur", "Premier League", "DEF", 24),
  p("Achraf Hakimi", "Morocco", "ma", "Paris Saint-Germain", "Ligue 1", "DEF", 27),
  p("Eberechi Eze", "England", "gb-eng", "Arsenal", "Premier League", "MID", 27),
  p("Serhou Guirassy", "Guinea", "gn", "Borussia Dortmund", "Bundesliga", "FWD", 29),
  p("Dušan Vlahović", "Serbia", "rs", "Juventus", "Serie A", "FWD", 25),
  p("Khéphren Thuram", "France", "fr", "Juventus", "Serie A", "MID", 24),
  p("Martín Zubimendi", "Spain", "es", "Arsenal", "Premier League", "MID", 26),
  p("Brahim Díaz", "Morocco", "ma", "Real Madrid", "La Liga", "MID", 26),
  p("Endrick", "Brazil", "br", "Real Madrid", "La Liga", "FWD", 19),
  p("Fermín López", "Spain", "es", "Barcelona", "La Liga", "MID", 22),
  p("Frenkie de Jong", "Netherlands", "nl", "Barcelona", "La Liga", "MID", 28),
  p("Fabián Ruiz", "Spain", "es", "Paris Saint-Germain", "Ligue 1", "MID", 29),
  p("Rúben Dias", "Portugal", "pt", "Manchester City", "Premier League", "DEF", 28),
  p("Dayot Upamecano", "France", "fr", "Bayern Munich", "Bundesliga", "DEF", 27),
  p("Alphonso Davies", "Canada", "ca", "Bayern Munich", "Bundesliga", "DEF", 25),
  p("Takefusa Kubo", "Japan", "jp", "Real Sociedad", "La Liga", "FWD", 24),
  p("Estêvão", "Brazil", "br", "Chelsea", "Premier League", "FWD", 18),
  p("Federico Dimarco", "Italy", "it", "Inter", "Serie A", "DEF", 28),
  p("Gabriel Martinelli", "Brazil", "br", "Arsenal", "Premier League", "FWD", 24),
  p("Cristian Romero", "Argentina", "ar", "Tottenham Hotspur", "Premier League", "DEF", 27),
  p("Ibrahima Konaté", "France", "fr", "Liverpool", "Premier League", "DEF", 26),
  p("Levi Colwill", "England", "gb-eng", "Chelsea", "Premier League", "DEF", 23),
  p("Anthony Gordon", "England", "gb-eng", "Newcastle United", "Premier League", "FWD", 25),
  p("Mohammed Kudus", "Ghana", "gh", "Tottenham Hotspur", "Premier League", "MID", 25),
  p("Ademola Lookman", "Nigeria", "ng", "Atalanta", "Serie A", "FWD", 28),
  p("Nicolas Jackson", "Senegal", "sn", "Chelsea", "Premier League", "FWD", 24),
  p("João Pedro", "Brazil", "br", "Chelsea", "Premier League", "FWD", 24),
  p("Kaoru Mitoma", "Japan", "jp", "Brighton", "Premier League", "FWD", 28),
  p("Joshua Kimmich", "Germany", "de", "Bayern Munich", "Bundesliga", "MID", 31),
  p("Bruno Fernandes", "Portugal", "pt", "Manchester United", "Premier League", "MID", 31),
  p("Pedro Neto", "Portugal", "pt", "Chelsea", "Premier League", "FWD", 26),
  p("Gonçalo Ramos", "Portugal", "pt", "Paris Saint-Germain", "Ligue 1", "FWD", 24),
  p("Éder Militão", "Brazil", "br", "Real Madrid", "La Liga", "DEF", 28),
  p("Jonathan David", "Canada", "ca", "Juventus", "Serie A", "FWD", 26),
  p("Randal Kolo Muani", "France", "fr", "Juventus", "Serie A", "FWD", 27),
  p("Amadou Onana", "Belgium", "be", "Aston Villa", "Premier League", "MID", 24),
  p("Ollie Watkins", "England", "gb-eng", "Aston Villa", "Premier League", "FWD", 30),
  p("Morgan Rogers", "England", "gb-eng", "Aston Villa", "Premier League", "MID", 23),
  p("Mikel Oyarzabal", "Spain", "es", "Real Sociedad", "La Liga", "FWD", 29),
  p("Mikel Merino", "Spain", "es", "Arsenal", "Premier League", "MID", 30),
  p("Marc Guéhi", "England", "gb-eng", "Crystal Palace", "Premier League", "DEF", 25),
  p("Pape Matar Sarr", "Senegal", "sn", "Tottenham Hotspur", "Premier League", "MID", 23),
  p("Victor Boniface", "Nigeria", "ng", "Bayer Leverkusen", "Bundesliga", "FWD", 25),
  p("Manu Koné", "France", "fr", "AS Roma", "Serie A", "MID", 25),
  p("Christopher Nkunku", "France", "fr", "AC Milan", "Serie A", "FWD", 28),
  p("Franco Mastantuono", "Argentina", "ar", "Real Madrid", "La Liga", "MID", 18),
  p("Christian Pulisic", "United States", "us", "AC Milan", "Serie A", "FWD", 27),
  p("Gregor Kobel", "Switzerland", "ch", "Borussia Dortmund", "Bundesliga", "GK", 28),
  p("Ferran Torres", "Spain", "es", "Barcelona", "La Liga", "FWD", 26),
  p("Karim Adeyemi", "Germany", "de", "Borussia Dortmund", "Bundesliga", "FWD", 24),
  p("Hakan Çalhanoğlu", "Turkey", "tr", "Inter", "Serie A", "MID", 32),
  p("Santiago Giménez", "Mexico", "mx", "AC Milan", "Serie A", "FWD", 25),
  p("Mike Maignan", "France", "fr", "AC Milan", "Serie A", "GK", 30),
  p("Gianluigi Donnarumma", "Italy", "it", "Manchester City", "Premier League", "GK", 27),
  p("Denzel Dumfries", "Netherlands", "nl", "Inter", "Serie A", "DEF", 30),
  p("Folarin Balogun", "United States", "us", "AS Monaco", "Ligue 1", "FWD", 24),
  p("Youri Tielemans", "Belgium", "be", "Aston Villa", "Premier League", "MID", 29),
  p("Jarrod Bowen", "England", "gb-eng", "West Ham", "Premier League", "FWD", 29),
  p("Scott McTominay", "Scotland", "gb-sct", "Napoli", "Serie A", "MID", 29),
  p("Theo Hernández", "France", "fr", "Al-Hilal", "Saudi Pro League", "DEF", 28),
  p("Leroy Sané", "Germany", "de", "Galatasaray", "Other", "FWD", 30),
  p("Tyler Adams", "United States", "us", "Bournemouth", "Premier League", "MID", 27),
  p("Antonee Robinson", "United States", "us", "Fulham", "Premier League", "DEF", 28),
  p("Edson Álvarez", "Mexico", "mx", "West Ham", "Premier League", "MID", 28),
  p("Weston McKennie", "United States", "us", "Juventus", "Serie A", "MID", 27),
  p("Kevin De Bruyne", "Belgium", "be", "Napoli", "Serie A", "MID", 34),
  p("Romelu Lukaku", "Belgium", "be", "Napoli", "Serie A", "FWD", 32),
  p("Antonio Rüdiger", "Germany", "de", "Real Madrid", "La Liga", "DEF", 33),
  p("Thibaut Courtois", "Belgium", "be", "Real Madrid", "La Liga", "GK", 33),
  p("Lionel Messi", "Argentina", "ar", "Inter Miami", "MLS", "FWD", 38),
  p("Neymar", "Brazil", "br", "Santos", "Other", "FWD", 34),
  p("Emiliano Martínez", "Argentina", "ar", "Aston Villa", "Premier League", "GK", 33),
  p("Alisson", "Brazil", "br", "Liverpool", "Premier League", "GK", 33),
  p("Robert Lewandowski", "Poland", "pl", "Barcelona", "La Liga", "FWD", 37),
  p("Heung-min Son", "South Korea", "kr", "Los Angeles FC", "MLS", "FWD", 33),
  p("Cristiano Ronaldo", "Portugal", "pt", "Al-Nassr", "Saudi Pro League", "FWD", 41),
  p("Álvaro Morata", "Spain", "es", "Como", "Serie A", "FWD", 33),
  p("Sadio Mané", "Senegal", "sn", "Al-Nassr", "Saudi Pro League", "FWD", 34),
  p("Wataru Endo", "Japan", "jp", "Liverpool", "Premier League", "MID", 33),
  p("Luka Modrić", "Croatia", "hr", "AC Milan", "Serie A", "MID", 40),
  p("Virgil van Dijk", "Netherlands", "nl", "Liverpool", "Premier League", "DEF", 34),
  p("Mohamed Salah", "Egypt", "eg", "Liverpool", "Premier League", "FWD", 33),
  p("Nico Williams", "Spain", "es", "Athletic Club", "La Liga", "FWD", 23),
  p("Warren Zaïre-Emery", "France", "fr", "Paris Saint-Germain", "Ligue 1", "MID", 20),
  p("Jeremie Frimpong", "Netherlands", "nl", "Liverpool", "Premier League", "DEF", 25),
  p("Nico Schlotterbeck", "Germany", "de", "Borussia Dortmund", "Bundesliga", "DEF", 26),
  p("Diogo Costa", "Portugal", "pt", "Porto", "Other", "GK", 26),
  p("Adam Wharton", "England", "gb-eng", "Crystal Palace", "Premier League", "MID", 21),
];

export const POSITION_LABEL: Record<Position, string> = {
  GK: "Goalkeeper",
  DEF: "Defender",
  MID: "Midfielder",
  FWD: "Forward",
};
